### ISSUE TITLE
[Q] Is it possible to hide a specific absolute path? Instead of all files matching a certain name or prefix?

### ISSUE THREAD

**Issue by xplshn** [PhOenIx20069/Merlin#1]

**Comment by PhOenIx20069** [comment]
Probably
you must change prefix to hide by your absolute path and try
You can add other pattern to hide

**Comment by xplshn** [comment]
Alreadyy tried, that does not work, filldir64 doesn't work with absolute paths, but it is possible, I just don't know how to implement it (see the Gobohide Linux kernel patch)
